/**
 * <auto-generated>
 * Autogenerated by Thrift Compiler (0.16.0)
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 * </auto-generated>
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using Thrift;
using Thrift.Collections;

using Thrift.Protocol;
using Thrift.Protocol.Entities;
using Thrift.Protocol.Utilities;
using Thrift.Transport;
using Thrift.Transport.Client;
using Thrift.Transport.Server;
using Thrift.Processor;


#nullable disable                // suppress C# 8.0 nullable contexts (we still support earlier versions)
#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable IDE0083  // pattern matching "that is not SomeType" requires net5.0 but we still support earlier versions

namespace Evernote.EDAM.NoteStore
{

  /// <summary>
  /// The return value of a call to the manageNoteShares function.
  /// 
  /// <dl>
  ///   <dt>errors</dt>
  ///   <dd>If the call succeeded without throwing an exception, some errors
  ///     might still have occurred. In that case, this field will contain the
  ///     list of errors.</dd>
  /// </dl>
  /// </summary>
  public partial class ManageNoteSharesResult : TBase
  {
    private List<global::Evernote.EDAM.NoteStore.ManageNoteSharesError> _errors;

    public List<global::Evernote.EDAM.NoteStore.ManageNoteSharesError> Errors
    {
      get
      {
        return _errors;
      }
      set
      {
        __isset.errors = true;
        this._errors = value;
      }
    }


    public Isset __isset;
    public struct Isset
    {
      public bool errors;
    }

    public ManageNoteSharesResult()
    {
    }

    public ManageNoteSharesResult DeepCopy()
    {
      var tmp346 = new ManageNoteSharesResult();
      if((Errors != null) && __isset.errors)
      {
        tmp346.Errors = this.Errors.DeepCopy();
      }
      tmp346.__isset.errors = this.__isset.errors;
      return tmp346;
    }

    public async global::System.Threading.Tasks.Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        await iprot.ReadStructBeginAsync(cancellationToken);
        while (true)
        {
          field = await iprot.ReadFieldBeginAsync(cancellationToken);
          if (field.Type == TType.Stop)
          {
            break;
          }

          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.List)
              {
                {
                  TList _list347 = await iprot.ReadListBeginAsync(cancellationToken);
                  Errors = new List<global::Evernote.EDAM.NoteStore.ManageNoteSharesError>(_list347.Count);
                  for(int _i348 = 0; _i348 < _list347.Count; ++_i348)
                  {
                    global::Evernote.EDAM.NoteStore.ManageNoteSharesError _elem349;
                    _elem349 = new global::Evernote.EDAM.NoteStore.ManageNoteSharesError();
                    await _elem349.ReadAsync(iprot, cancellationToken);
                    Errors.Add(_elem349);
                  }
                  await iprot.ReadListEndAsync(cancellationToken);
                }
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            default: 
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              break;
          }

          await iprot.ReadFieldEndAsync(cancellationToken);
        }

        await iprot.ReadStructEndAsync(cancellationToken);
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public async global::System.Threading.Tasks.Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
    {
      oprot.IncrementRecursionDepth();
      try
      {
        var tmp350 = new TStruct("ManageNoteSharesResult");
        await oprot.WriteStructBeginAsync(tmp350, cancellationToken);
        var tmp351 = new TField();
        if((Errors != null) && __isset.errors)
        {
          tmp351.Name = "errors";
          tmp351.Type = TType.List;
          tmp351.ID = 1;
          await oprot.WriteFieldBeginAsync(tmp351, cancellationToken);
          {
            await oprot.WriteListBeginAsync(new TList(TType.Struct, Errors.Count), cancellationToken);
            foreach (global::Evernote.EDAM.NoteStore.ManageNoteSharesError _iter352 in Errors)
            {
              await _iter352.WriteAsync(oprot, cancellationToken);
            }
            await oprot.WriteListEndAsync(cancellationToken);
          }
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        await oprot.WriteFieldStopAsync(cancellationToken);
        await oprot.WriteStructEndAsync(cancellationToken);
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override bool Equals(object that)
    {
      if (!(that is ManageNoteSharesResult other)) return false;
      if (ReferenceEquals(this, other)) return true;
      return ((__isset.errors == other.__isset.errors) && ((!__isset.errors) || (TCollections.Equals(Errors, other.Errors))));
    }

    public override int GetHashCode() {
      int hashcode = 157;
      unchecked {
        if((Errors != null) && __isset.errors)
        {
          hashcode = (hashcode * 397) + TCollections.GetHashCode(Errors);
        }
      }
      return hashcode;
    }

    public override string ToString()
    {
      var tmp353 = new StringBuilder("ManageNoteSharesResult(");
      int tmp354 = 0;
      if((Errors != null) && __isset.errors)
      {
        if(0 < tmp354++) { tmp353.Append(", "); }
        tmp353.Append("Errors: ");
        Errors.ToString(tmp353);
      }
      tmp353.Append(')');
      return tmp353.ToString();
    }
  }

}
