/**
 * <auto-generated>
 * Autogenerated by Thrift Compiler (0.16.0)
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 * </auto-generated>
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using Thrift;
using Thrift.Collections;

using Thrift.Protocol;
using Thrift.Protocol.Entities;
using Thrift.Protocol.Utilities;
using Thrift.Transport;
using Thrift.Transport.Client;
using Thrift.Transport.Server;
using Thrift.Processor;


#nullable disable                // suppress C# 8.0 nullable contexts (we still support earlier versions)
#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable IDE0083  // pattern matching "that is not SomeType" requires net5.0 but we still support earlier versions

namespace Evernote.EDAM.NoteStore
{

  /// <summary>
  /// Captures a collection of share relationships for a single note,
  /// for example, as returned by the getNoteShares method. The share
  /// relationships fall into two broad categories: members, and
  /// invitations that can be used to become members.
  /// 
  /// <dl>
  /// <dt>invitations</dt>
  /// <dd>A list of open invitations that can be redeemed into
  /// memberships to the note.</dd>
  /// 
  /// <dt>memberships</dt>
  /// <dd>A list of memberships of the noteb. A member is identified
  /// by their Evernote UserID and has rights to access the
  /// note.</dd>
  /// 
  /// <dt>restrictions</dt>
  /// <dd>The restrictions on which privileges may be assigned to the recipient
  /// of an open invitation. These restrictions only apply to invitations;
  /// restrictions on memberships are specified on the NoteMemberShareRelationship.
  /// This field is used by the service to convey information to the user, so
  /// clients should treat it as read-only.</dd>
  /// 
  /// </dl>
  /// </summary>
  public partial class NoteShareRelationships : TBase
  {
    private List<global::Evernote.EDAM.NoteStore.NoteInvitationShareRelationship> _invitations;
    private List<global::Evernote.EDAM.NoteStore.NoteMemberShareRelationship> _memberships;
    private global::Evernote.EDAM.NoteStore.NoteShareRelationshipRestrictions _invitationRestrictions;

    public List<global::Evernote.EDAM.NoteStore.NoteInvitationShareRelationship> Invitations
    {
      get
      {
        return _invitations;
      }
      set
      {
        __isset.invitations = true;
        this._invitations = value;
      }
    }

    public List<global::Evernote.EDAM.NoteStore.NoteMemberShareRelationship> Memberships
    {
      get
      {
        return _memberships;
      }
      set
      {
        __isset.memberships = true;
        this._memberships = value;
      }
    }

    public global::Evernote.EDAM.NoteStore.NoteShareRelationshipRestrictions InvitationRestrictions
    {
      get
      {
        return _invitationRestrictions;
      }
      set
      {
        __isset.invitationRestrictions = true;
        this._invitationRestrictions = value;
      }
    }


    public Isset __isset;
    public struct Isset
    {
      public bool invitations;
      public bool memberships;
      public bool invitationRestrictions;
    }

    public NoteShareRelationships()
    {
    }

    public NoteShareRelationships DeepCopy()
    {
      var tmp307 = new NoteShareRelationships();
      if((Invitations != null) && __isset.invitations)
      {
        tmp307.Invitations = this.Invitations.DeepCopy();
      }
      tmp307.__isset.invitations = this.__isset.invitations;
      if((Memberships != null) && __isset.memberships)
      {
        tmp307.Memberships = this.Memberships.DeepCopy();
      }
      tmp307.__isset.memberships = this.__isset.memberships;
      if((InvitationRestrictions != null) && __isset.invitationRestrictions)
      {
        tmp307.InvitationRestrictions = (global::Evernote.EDAM.NoteStore.NoteShareRelationshipRestrictions)this.InvitationRestrictions.DeepCopy();
      }
      tmp307.__isset.invitationRestrictions = this.__isset.invitationRestrictions;
      return tmp307;
    }

    public async global::System.Threading.Tasks.Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        await iprot.ReadStructBeginAsync(cancellationToken);
        while (true)
        {
          field = await iprot.ReadFieldBeginAsync(cancellationToken);
          if (field.Type == TType.Stop)
          {
            break;
          }

          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.List)
              {
                {
                  TList _list308 = await iprot.ReadListBeginAsync(cancellationToken);
                  Invitations = new List<global::Evernote.EDAM.NoteStore.NoteInvitationShareRelationship>(_list308.Count);
                  for(int _i309 = 0; _i309 < _list308.Count; ++_i309)
                  {
                    global::Evernote.EDAM.NoteStore.NoteInvitationShareRelationship _elem310;
                    _elem310 = new global::Evernote.EDAM.NoteStore.NoteInvitationShareRelationship();
                    await _elem310.ReadAsync(iprot, cancellationToken);
                    Invitations.Add(_elem310);
                  }
                  await iprot.ReadListEndAsync(cancellationToken);
                }
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 2:
              if (field.Type == TType.List)
              {
                {
                  TList _list311 = await iprot.ReadListBeginAsync(cancellationToken);
                  Memberships = new List<global::Evernote.EDAM.NoteStore.NoteMemberShareRelationship>(_list311.Count);
                  for(int _i312 = 0; _i312 < _list311.Count; ++_i312)
                  {
                    global::Evernote.EDAM.NoteStore.NoteMemberShareRelationship _elem313;
                    _elem313 = new global::Evernote.EDAM.NoteStore.NoteMemberShareRelationship();
                    await _elem313.ReadAsync(iprot, cancellationToken);
                    Memberships.Add(_elem313);
                  }
                  await iprot.ReadListEndAsync(cancellationToken);
                }
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 3:
              if (field.Type == TType.Struct)
              {
                InvitationRestrictions = new global::Evernote.EDAM.NoteStore.NoteShareRelationshipRestrictions();
                await InvitationRestrictions.ReadAsync(iprot, cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            default: 
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              break;
          }

          await iprot.ReadFieldEndAsync(cancellationToken);
        }

        await iprot.ReadStructEndAsync(cancellationToken);
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public async global::System.Threading.Tasks.Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
    {
      oprot.IncrementRecursionDepth();
      try
      {
        var tmp314 = new TStruct("NoteShareRelationships");
        await oprot.WriteStructBeginAsync(tmp314, cancellationToken);
        var tmp315 = new TField();
        if((Invitations != null) && __isset.invitations)
        {
          tmp315.Name = "invitations";
          tmp315.Type = TType.List;
          tmp315.ID = 1;
          await oprot.WriteFieldBeginAsync(tmp315, cancellationToken);
          {
            await oprot.WriteListBeginAsync(new TList(TType.Struct, Invitations.Count), cancellationToken);
            foreach (global::Evernote.EDAM.NoteStore.NoteInvitationShareRelationship _iter316 in Invitations)
            {
              await _iter316.WriteAsync(oprot, cancellationToken);
            }
            await oprot.WriteListEndAsync(cancellationToken);
          }
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        if((Memberships != null) && __isset.memberships)
        {
          tmp315.Name = "memberships";
          tmp315.Type = TType.List;
          tmp315.ID = 2;
          await oprot.WriteFieldBeginAsync(tmp315, cancellationToken);
          {
            await oprot.WriteListBeginAsync(new TList(TType.Struct, Memberships.Count), cancellationToken);
            foreach (global::Evernote.EDAM.NoteStore.NoteMemberShareRelationship _iter317 in Memberships)
            {
              await _iter317.WriteAsync(oprot, cancellationToken);
            }
            await oprot.WriteListEndAsync(cancellationToken);
          }
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        if((InvitationRestrictions != null) && __isset.invitationRestrictions)
        {
          tmp315.Name = "invitationRestrictions";
          tmp315.Type = TType.Struct;
          tmp315.ID = 3;
          await oprot.WriteFieldBeginAsync(tmp315, cancellationToken);
          await InvitationRestrictions.WriteAsync(oprot, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        await oprot.WriteFieldStopAsync(cancellationToken);
        await oprot.WriteStructEndAsync(cancellationToken);
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override bool Equals(object that)
    {
      if (!(that is NoteShareRelationships other)) return false;
      if (ReferenceEquals(this, other)) return true;
      return ((__isset.invitations == other.__isset.invitations) && ((!__isset.invitations) || (TCollections.Equals(Invitations, other.Invitations))))
        && ((__isset.memberships == other.__isset.memberships) && ((!__isset.memberships) || (TCollections.Equals(Memberships, other.Memberships))))
        && ((__isset.invitationRestrictions == other.__isset.invitationRestrictions) && ((!__isset.invitationRestrictions) || (global::System.Object.Equals(InvitationRestrictions, other.InvitationRestrictions))));
    }

    public override int GetHashCode() {
      int hashcode = 157;
      unchecked {
        if((Invitations != null) && __isset.invitations)
        {
          hashcode = (hashcode * 397) + TCollections.GetHashCode(Invitations);
        }
        if((Memberships != null) && __isset.memberships)
        {
          hashcode = (hashcode * 397) + TCollections.GetHashCode(Memberships);
        }
        if((InvitationRestrictions != null) && __isset.invitationRestrictions)
        {
          hashcode = (hashcode * 397) + InvitationRestrictions.GetHashCode();
        }
      }
      return hashcode;
    }

    public override string ToString()
    {
      var tmp318 = new StringBuilder("NoteShareRelationships(");
      int tmp319 = 0;
      if((Invitations != null) && __isset.invitations)
      {
        if(0 < tmp319++) { tmp318.Append(", "); }
        tmp318.Append("Invitations: ");
        Invitations.ToString(tmp318);
      }
      if((Memberships != null) && __isset.memberships)
      {
        if(0 < tmp319++) { tmp318.Append(", "); }
        tmp318.Append("Memberships: ");
        Memberships.ToString(tmp318);
      }
      if((InvitationRestrictions != null) && __isset.invitationRestrictions)
      {
        if(0 < tmp319++) { tmp318.Append(", "); }
        tmp318.Append("InvitationRestrictions: ");
        InvitationRestrictions.ToString(tmp318);
      }
      tmp318.Append(')');
      return tmp318.ToString();
    }
  }

}
