/**
 * <auto-generated>
 * Autogenerated by Thrift Compiler (0.16.0)
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 * </auto-generated>
 */

#nullable disable                // suppress C# 8.0 nullable contexts (we still support earlier versions)
#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable IDE0083  // pattern matching "that is not SomeType" requires net5.0 but we still support earlier versions

namespace Evernote.EDAM.Type
{
  /// <summary>
  /// This enumeration defines the possible states that a notebook can be in for a recipient.
  /// It encompasses the "inMyList" boolean and default notebook status.
  /// 
  /// <dl>
  /// <dt>NOT_IN_MY_LIST</dt>
  /// <dd>The notebook is not in the recipient's list (not "joined").</dd>
  /// <dt>IN_MY_LIST</dt>
  /// <dd>The notebook is in the recipient's notebook list (formerly, we would say
  ///     that the recipient has "joined" the notebook)</dd>
  /// <dt>IN_MY_LIST_AND_DEFAULT_NOTEBOOK</dt>
  /// <dd>The same as IN_MY_LIST and this notebook is the user's default notebook.</dd>
  /// </dl>
  /// </summary>
  public enum RecipientStatus
  {
    NOT_IN_MY_LIST = 1,
    IN_MY_LIST = 2,
    IN_MY_LIST_AND_DEFAULT_NOTEBOOK = 3,
  }
}
